### ISSUE TITLE
template error results in no boom

### ISSUE THREAD

**Issue by ugate** [hapijs/vision#76] opened 2016-02-17 21:08 UTC
When `compiled.template` throws an Error it's handled via Hapi's `fail` function within `transmit.js` which causes a new `Response` to be generated. By the time that this new response is propagated to `onPreResponse` listeners there is no indication that an error has occurred via `request.response.isBoom`.

Hapi v13.0.0
Vision v4.0.1

**Comment by jagoda** [comment] 2016-02-21 00:37
Can you please provides some more details around your specific scenario? Steps to reproduce would be ideal. At first glance this looks like a bad template engine implementation rather than an issue with vision.

**Comment by jagoda** [comment] 2016-04-04 11:55
@ugate without more information it's hard to be sure what your issue is. Could you provide more details like which template engine you are using and what scenario causes the template to throw an error (and does it actually throw or callback with an error)? The best info would be steps to reproduce. Without this extra information I'm inclined to assume that this is just a bad template engine implementation and will close the issue.

**Comment by ugate** [comment] 2016-04-04 23:16
@jagoda I'll try to put something together and post here

**Comment by jagoda** [comment] 2016-04-25 19:32
Any luck?

**Closed** 2016-05-04 13:20 UTC
Labels: non issue
