### ISSUE TITLE
Support handler to rescue render errors?

### ISSUE THREAD

**Issue by novemberborn** [hapijs/vision#106] opened 2016-12-01 16:13 UTC
Per #96, views are rendered lazily, when the response is transmitted. At that point it's too late to intercept any render errors and replace them with a nice error page. The workaround seems to be to call `request.render()` manually and then call `reply()` with the rendered result.

This seems to negate a fair amount of the value that Vision provides. For one views may be rendered prematurely. Projects may also find it easier to forgo Vision and set up their own reply decorator that handles all of this directly.

Perhaps Vision could support a handler to rescue such render errors? It would receive the error and the reply / response, allowing it to send an alternative response instead.

**Comment by sholladay** [comment] 2017-02-21 04:20
Wouldn't a better fix be to delay `onPreResponse` until after the template has been rendered? That seems more logical and consistent to me. Not sure if this is an issue in core or in `vision`.

**Comment by jwdotjs** [comment] 2017-02-27 14:30
The below solution is pretty hacky since I didn't feel comfortable modifying Vision or Hapi, but I got this working by providing a compiler that uses the templating engine's compiler and catches any compilation errors, then renders a template that displays the compilation error in browser. 

```javascript
views: {
    engines: {
      pug: {
        module: {
          compile(...args) {
            const template = pug.compile.apply(null, args);
            const compileFn = function compileFn(locals) {
              if (process.env.NODE_ENV !== 'development') {
                return template(locals);
              }
              try {
                return template(locals);
              } catch (compilationError) {
                console.error(compilationError); // eslint-disable-line
                const stackTrace = compilationError.stack.split('\n');
                return pug.renderFile('path/to/development-compilation-error-template', {stackTrace});
              }
            };
            return compileFn;
          },
        },
      },
    },
```

**Comment by bschwartz757** [comment] 2018-01-18 23:05
@wswoodruff @jwdotjs It would be great if this could be addressed by the Vision and/or HapiJS documentation. I'm currently using Hapi 16.6.2 (haven't upgraded yet because some custom plugins we use will need to be re-written for v17) and after a couple of hours sifting through Vision & Hapi docs (and trying @jwdotjs 's method above) the only thing I've managed to get working is this:
```
  server.views({
    engines: {
      pug: require('pug')
    },
    relativeTo: __dirname,
    isCached: false,
    path: 'src'
  })

  server.route({
    method: 'GET',
    path: '/',
    handler: function (request, h) {
      const context = {
        beta: beta
      }
      try {
        return request.render('index', context, (err, rendered, config) => {
          if (err) {
            throw new Error(err)
          }
          return h.view('index', context)
        })
      } catch (err) {
        console.log(err)
      }
    }
  })
```
which is surely an abomination, but does get me a nice stack trace. Previously, when just calling `return h.view('index', context)` if a compile error was thrown I wouldn't see anything in the terminal - just a 500 error in the browser, and the server looked as if it was still humming along. I'm using Gulp and opn and was previously compiling pug in Gulp, which threw errors if parsing failed. In my case all I want to do is crash the server if this happens, so I don't go searching for unrelated errors.

Please share if you can think of a better workaround.

**Comment by TheJimFactor** [comment] 2018-04-19 23:34
Hi, I was having this issue as well. I was trying to get compile errors for pug and found that adding:

    ```javascript
    server.log(['error'])

would display the pug compile errors. Should work for other compile engines as well.

**Comment by SimonSchick** [comment] 2018-06-05 10:10
I am running into the same issue, can we please get a `failAction` error handler on the vision plugin?
I do agree the `onPreResponse` being called before the _actual_ response is generated is somewhat misleading, @hueniverse I assume this is by design but would it be possible to perhaps introduce a lifecycle event that received only the _final_ response returned by the `prepare` function?

**Comment by wswoodruff** [comment] 2018-08-10 13:15
I revisited this issue when working through some of the older issues here on Vision. The solution I think most closely matches the requirements here would be to allow you to pass a `compileErrTransform` func on your `server.views({...})` call (in the opts that get passed to the Manager).

This func would pass in the compile error, then allow you to return either a different error or return a valid compiled view. If an error happens in compilation for this handler tho, that will be the new error that gets passed through.

Open to suggestions or thoughts on how to handle this, since we're using request marshaling it seems to be throwing off the regular hooks like `onPreResponse` and `failAction`

**Comment by ishanyang** [comment] 2018-10-20 01:05
#### lifecycle **onPreResponse** *to handle view errors*
```JavaScript
const viewNotFoundReg = /View file not found(.*)H-ui.admin\/(.*).pug/ig
server.ext('onPreResponse', (request, h) => {
  if(viewNotFoundReg.test(request.response.message)){
    return h.view('H-ui.admin/404', {
      title:"404 not found",
      statusCode: 404,
      errName: "Not found"
    })
  }
  // ...else if...
  return h.continue;
});
```

**Comment by hueniverse** [comment] 2018-11-06 06:20
We can't keep adding more lifecycle steps in case other lifecycle steps fail...

`onPreResponse` is the last time you get a chance to modify the response. A typical use case is to change the context of the response before rendering in the final lifecycle step.

In order to give a bit more control, the response comes with its own two lifecycle methods: `prepare` and `marshal`. `prepare` is called on the next tick after the response is passed to hapi. `marshal` is called right before transmission.

Ideally, you perform all operations that can error in `prepare` and keep `marshal` as error free as possible. However, it is possible for `prepare` to verify and compile a template while `marshal` errors due to invalid context passed at rendering time.

`marshal` already allows you to return anything else back. If you want to allow developers to deal with errors raised during marshal, that's where you want to invoke a failAction handler.

**Comment by hueniverse** [comment] 2019-04-08 22:16
Closing due to inactivity.

**Closed by hueniverse** 2019-04-08 22:16 UTC
Labels: enhancement, request

**Comment by yuvke** [comment] 2019-12-03 13:59
@wswoodruff , the solution above by @bschwartz757 doesn't work. It seems that the render function no longer accepts the fourth optional callback parameter. At least that's what I see here:

https://github.com/hapijs/vision/blob/master/lib/index.js#L89

Is this a bug? Is there another way to accommodate this need?

**Comment by wswoodruff** [comment] 2019-12-03 14:26
@yuvke Yeah the `render` func has since been moved to async — the idea with `bschwartz757`'s approach is to call `render` yourself and catch and respond with the error however you want — could be returning a `Boom` error or rendering another template.

**Comment by yuvke** [comment] 2019-12-03 17:48
Thanks @wswoodruff. It might be worth updating the vision docs since it took a while to debug this.

**Comment by hueniverse** [comment] 2019-12-03 18:53
@yuvke PRs are welcomed!
