### ISSUE TITLE
Can we get the latest commits pushed to NPM?

### ISSUE THREAD

**Issue by ADumaine** [hapijs/vision#95] opened 2016-07-07 21:44 UTC
I have 4.1.0 but am looking for the Hoek.isAbsolutePath(path) replacement.

Thanks!

**Comment by lloydbenson** [comment] 2016-07-07 21:51
Try Hoek.isAbsolute(path)

**Comment by ADumaine** [comment] 2016-07-07 22:43
I just reverted to 4.0.1 for now.  I'll try again once the next version is available.

**Comment by jagoda** [comment] 2016-07-14 12:32
Can you help me understand why this is needed? The use of hoek is entirely internal to vision, so I wouldn't expect this to have any external impact.

**Comment by ADumaine** [comment] 2016-07-14 18:01
There may be two things separate parts here.  

Item #1:
My project  throws an error on manager.js line 519 after vision was updated to 4.1.0 and Hoek to 4.0.1. 

```
TypeError: Hoek.isAbsolutePath is not a function
```
I think this a dependency  or update sequence issue.  It happens if vision is updated to latest before Hoek 3.x is updated to 4.x which no longer longer has isAbsolutePath.  Reinstalling vision (4.0.1) causes Hoek 3.0.4 to be installed under it, allowing it work.

```
vision@4.0.1 node_modules\vision
├── items@2.1.0
├── hoek@3.0.4
└── joi@7.3.0 (isemail@2.2.0, topo@2.0.1)
```

Item #2:
The package.json for vision 4.1.0 in my project calls for hoek 3.x.x.  I have removed vision from my project and deleted the npm cache for vision.  After installing vision again (it is not installed globally) I still see hoek 3.x.x but the package.json on github shows 4.x.x.   Why is it still at hoek 3.x?

```
vision@4.1.0 node_modules\vision
├── items@2.1.0
└── hoek@3.0.4
```

Here's my newest package.json after installing vision@latest:
```
{
  "name": "vision",
  "description": "Templates rendering plugin support for hapi.js",
  "version": "4.1.0",
  "repository": {
    "type": "git",
    "url": "git://github.com/hapijs/vision.git"
  },
  "main": "lib/index.js",
  "keywords": [
    "view",
    "render",
    "template",
    "hapi"
  ],
  "engines": {
    "node": ">=4.0.0"
  },
  "dependencies": {
    "boom": "3.x.x",
    "hoek": "3.x.x",
    "items": "2.x.x",
    "joi": "8.x.x"
  },
  "devDependencies": {
    "babel-core": "6.x.x",
    "babel-plugin-transform-react-jsx": "6.x.x",
    "code": "2.x.x",
    "ejs": "2.x.x",
    "handlebars": "4.x.x",
    "hapi": "13.x.x",
    "hapi-react-views": "6.x.x",
    "jade": "1.x.x",
    "lab": "10.x.x",
    "marko": "3.x.x",
    "mustache": "2.x.x",
    "nunjucks": "2.x.0",
    "react": "0.14.x",
    "react-dom": "0.14.x"
  },
  "scripts": {
    "test": "lab -a code -t 100 -L",
    "test-cov-html": "lab -a code -r html -o coverage.html"
  },
  "license": "BSD-3-Clause",
  "gitHead": "5747651957134458252750f1bef5a5a12c600276",
  "bugs": {
    "url": "https://github.com/hapijs/vision/issues"
  },
  "homepage": "https://github.com/hapijs/vision#readme",
  "_id": "vision@4.1.0",
  "_shasum": "c0c49c9287423cfcf7dbedf51ae6a67b065c6ae7",
  "_from": "vision@latest",
  "_npmVersion": "3.7.3",
  "_nodeVersion": "5.9.0",
  "_npmUser": {
    "name": "jagoda",
    "email": "jeffrey.jagoda@gmail.com"
  },
  "dist": {
    "shasum": "c0c49c9287423cfcf7dbedf51ae6a67b065c6ae7",
    "tarball": "https://registry.npmjs.org/vision/-/vision-4.1.0.tgz"
  },
  "maintainers": [
    {
      "name": "hueniverse",
      "email": "eran@hammer.io"
    },
    {
      "name": "jagoda",
      "email": "jeffrey.jagoda@gmail.com"
    }
  ],
  "_npmOperationalInternal": {
    "host": "packages-12-west.internal.npmjs.com",
    "tmp": "tmp/vision-4.1.0.tgz_1459802415218_0.9084511322434992"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/vision/-/vision-4.1.0.tgz"
}
```
This is why I did not think the latest commits were on npm.
Running on win 7, with npm v2.15.4 and node v4.4.5

**Comment by jagoda** [comment] 2016-07-15 00:44
> I think this a dependency or update sequence issue. It happens if vision is updated to latest before Hoek 3.x is updated to 4.x which no longer longer has isAbsolutePath.

How are you doing this update? It is true that the latest release depends on hoek 3.x (which means that if your app uses hoek 4.x vision will use it's own copy of hoek 3.x), but my understanding is that npm should normally handle this sort of thing automatically. This is in fact the whole idea behind specifying the dependency based on the major version number as changes to it represent a breaking API change.

> This is why I did not think the latest commits were on npm.

You are correct that the latest commits are not on npm. If you look at the [change history](https://github.com/hapijs/vision/commits/master) you will note that vision 4.1.0 was released on April 4 and then there were additional commits merged on May 3 and May 29. However, none of these commits were for functional changes (bug or enhancement) or modifications to external APIs and therefore shouldn't impact consumers. Thus, a new release didn't seem warranted.

**Comment by ADumaine** [comment] 2016-07-15 01:07
The updates were being done manually on the command line one at a time.  The application refreshes each time a change is made.

hoek 3.x was the current module.
vision@latest was installed.  Since hoek was already available it used the peer.
hoek@latest was installed updating hoek to 4.x.  vision no longer had 3.x as a peer and npm did not add hoek 3.x under it.  vision had to later be installed again to make that happen.

I found it confusing trying to trouble shoot.  I was looking for isAbsolutePath in the Hoek documentation and code and not finding.  It has been removed from the API, the npm package still uses it via 3.x, but this repository has been changed to use Path.  The stars were just not aligned for me....

**Comment by jagoda** [comment] 2016-07-15 12:48
> vision no longer had 3.x as a peer and npm did not add hoek 3.x under it. vision had to later be installed again to make that happen.

I was able to reproduce this on node 4.4.5 and npm 2.15.5. This seems like a bug in npm and not an issue with vision. When I use node 6.1.0 and npm 3.8.6 the problem is automatically corrected.

> I found it confusing trying to trouble shoot.

Understandable. Just for reference, you can always find a snapshot of the code for each release by switching the view from the master branch to the release tag. The code for 4.1.0 is [here](https://github.com/hapijs/vision/tree/v4.1.0).

**Closed by jagoda** 2016-07-15 12:48 UTC
Labels: non issue
